### ISSUE TITLE
"Become a member" and "Register" Buttons are not pointing anywhere

### ISSUE THREAD

**Issue by SoumavaBanerjee** [Hack-Club-UEMK/hackclub.github.io#12]
Become a member and Register buttons are refering back to the home screen. It would be nice if those were linked to some registration form or something like that

**Comment by krohan1202** [comment]
These buttons will point to the g-form when the students will come to become a member.
Solve this issue at the very end by just connecting the link

**Comment by Prasundas99** [comment]
issue open korar age khule dekh

**Comment by SoumavaBanerjee** [comment]
Oh ami purono deployment ta teh likhechilam 😂
