### ISSUE TITLE
Adjust Animation timing

### ISSUE THREAD

**Issue by SoumavaBanerjee** [Hack-Club-UEMK/hackclub.github.io#8]
### Issue:
The animation is kinda off on the web development and machine learning sections of the website. Customising the timing and offset of just those two sections might be one of the possible solutions.

**Comment by Shubhamdutta2000** [comment]
I want to solve this issue Plz assign me

**Comment by SoumavaBanerjee** [comment]
ya sure, go ahead

**Comment by Prasundas99** [comment]
Is the issue is still valid? 
If yes then I want to solve this issue Please assign me too

**Comment by SoumavaBanerjee** [comment]
@Shubhamdutta2000  is working on it.

**Comment by SoumavaBanerjee** [comment]
Okay, seems like the animations are fine now.
